export const fakeData09 = {
  apiData: {
    entId: 5,
    entName: "AREASEMIELABORADO",
    ordenes: [
      {
        Duracion: 0,
        FactorOEE: 1,
        ItemDesc: "Semielaborado 1",
        ItemId: "SEMI001",
        OperId: "NETEJA",
        Personas: 1,
        QtyProd: 0,
        QtyReqd: 1,
        RowId: 120,
        SchedStartTimeLocal: "2022-09-01T11:28:00",
        SeqNo: 0,
        StateCd: 2,
        StateCdDesc: "Ready",
        WoId: "20220328133630",
        matriculasCargadas: false,
        posiblesVelocidades: [
          {
            personas: 1,
            velocidad: 0,
          },
        ],
        target_EntId: 7,
        target_EntName: "L002",
        id: "b40783f-065e-d7db-f431-1a400b312b1b",
      },
      {
        Duracion: 282.2,
        FactorOEE: 0.59,
        ItemDesc: "Semielaborado 1",
        ItemId: "SEMI001",
        OperId: "AreaSemielaborado",
        Personas: 4,
        QtyProd: 0,
        QtyReqd: 15000,
        RowId: 121,
        SchedStartTimeLocal: "2022-09-01T11:27:52",
        SeqNo: 0,
        StateCd: 2,
        StateCdDesc: "Ready",
        WoId: "20220331091449",
        matriculasCargadas: false,
        posiblesVelocidades: [
          {
            personas: 1,
            velocidad: 66.66,
          },
          {
            personas: 2,
            velocidad: 33.33,
          },
          {
            personas: 3,
            velocidad: 22.22,
          },
          {
            personas: 4,
            velocidad: 11.1,
          },
        ],
        target_EntId: 6,
        target_EntName: "L001",
        id: "aec2727-130-6f7a-7033-4a6cc3ddbd0",
      },
      {
        Duracion: 0,
        FactorOEE: 1,
        ItemDesc: "Semielaborado 1",
        ItemId: "SEMI001",
        OperId: "NETEJA",
        Personas: 1,
        QtyProd: 0,
        QtyReqd: 1,
        RowId: 122,
        SchedStartTimeLocal: "2022-09-01T16:10:04",
        SeqNo: 0,
        StateCd: 2,
        StateCdDesc: "Ready",
        WoId: "20220331091449",
        matriculasCargadas: false,
        posiblesVelocidades: [
          {
            personas: 1,
            velocidad: 0,
          },
        ],
        target_EntId: 6,
        target_EntName: "L001",
        id: "ab7bfbb-d4fb-751-1cd7-8eb8d25ca6c",
      },
      {
        Duracion: 0,
        FactorOEE: 1,
        ItemDesc: "Semielaborado 1",
        ItemId: "SEMI001",
        OperId: "NETEJA",
        Personas: 1,
        QtyProd: 0,
        QtyReqd: 1,
        RowId: 124,
        SchedStartTimeLocal: "2022-09-01T11:27:51",
        SeqNo: 0,
        StateCd: 2,
        StateCdDesc: "Ready",
        WoId: "20220809120146",
        matriculasCargadas: false,
        posiblesVelocidades: [
          {
            personas: 1,
            velocidad: 0,
          },
        ],
        target_EntId: 6,
        target_EntName: "L001",
        id: "ebcfb57-bbe-61c-81bb-338a28d7fd",
      },
      {
        Duracion: 28.233333,
        FactorOEE: 0.59,
        ItemDesc: "Semielaborado 1",
        ItemId: "SEMI001",
        OperId: "AreaSemielaborado",
        Personas: 1,
        QtyProd: 0,
        QtyReqd: 250,
        RowId: 125,
        SchedStartTimeLocal: "2022-09-01T16:10:05",
        SeqNo: 0,
        StateCd: 2,
        StateCdDesc: "Ready",
        WoId: "20220809120444",
        matriculasCargadas: false,
        posiblesVelocidades: [
          {
            personas: 1,
            velocidad: 66.66,
          },
          {
            personas: 2,
            velocidad: 33.33,
          },
          {
            personas: 3,
            velocidad: 22.22,
          },
          {
            personas: 4,
            velocidad: 11.1,
          },
        ],
        target_EntId: 6,
        target_EntName: "L001",
        id: "05c330-2a82-f2ac-578-767a75a3ef52",
      },
      {
        Duracion: 1,
        FactorOEE: 1,
        ItemDesc: "Semielaborado 1",
        ItemId: "SEMI001",
        OperId: "NETEJA",
        Personas: 1,
        QtyProd: 0,
        QtyReqd: 1,
        RowId: 126,
        SchedStartTimeLocal: "2022-09-01T16:38:19",
        SeqNo: 0,
        StateCd: 2,
        StateCdDesc: "Ready",
        WoId: "20220809120444",
        matriculasCargadas: false,
        posiblesVelocidades: [
          {
            personas: 1,
            velocidad: 0,
          },
        ],
        target_EntId: 6,
        target_EntName: "L001",
        id: "ffcd3-1625-ae4-83f-eaa5c600242d",
      },
    ],
    lineas: [
      {
        entId: 6,
        entName: "L001",
        description: "Semielaborado 1",
        operacion: false,
        ordenes: "[]",
      },
      {
        entId: 7,
        entName: "L002",
        description: "Semielaborado 2",
        operacion: false,
        ordenes: "[]",
      },
    ],
  },
  teams: [
    {
      id: 6,
      title: "Semielaborado 1",
      stackItems: true,
    },
    {
      id: 7,
      title: "Semielaborado 2",
      stackItems: true,
    },
    {
      id: 5,
      title: "AREASEMIELABORADO",
    },
  ],
  timelineHours: 24,
  setSelected: "ƒ bound dispatchAction() {}",
};
