export const fakeData1 = [
  {
    entId: 5,
    entName: "AREASEMIELABORADO",
    ordenes: [
      {
        WoId: "20220310S000",
        OperId: "NETEJA",
        SeqNo: 0,
        RowId: 30,
        SeqNoRelacionadoSpare3: 0,
        debugSpare3: null,
        JobDesc: null,
        init_EntId: 5,
        init_EntName: "AreaSemielaborado",
        target_EntId: 6,
        target_EntName: "L001",
        run_EntId: 0,
        run_EntName: null,
        WoStateCd: 0,
        StateCd: 2,
        StateCdDesc: "Ready",
        ItemId: "SEMI001",
        ItemDesc: "Semielaborado 1",
        QtyReqd: 1,
        QtyProd: 0,
        Duracion: 0,
        Personas: 1,
        posiblesVelocidades: [
          {
            personas: 1,
            velocidad: 0,
          },
        ],
        FactorOEE: 1,
        matriculasCargadas: false,
        SchedStartTimeLocal: "2022-03-19T13:43:01",
        SchedFinishTimeLocal: "2022-03-19T13:43:01",
        ActStartTimeLocal: "0001-01-01T00:00:00",
        ActStartTimeUTC: "0001-01-01T00:00:00",
        JobPos: null,
      },
      {
        WoId: "20220319142243",
        OperId: "AreaSemielaborado",
        SeqNo: 0,
        RowId: 99,
        SeqNoRelacionadoSpare3: 0,
        debugSpare3: null,
        JobDesc: null,
        init_EntId: 5,
        init_EntName: "AreaSemielaborado",
        target_EntId: 6,
        target_EntName: "L001",
        run_EntId: 0,
        run_EntName: null,
        WoStateCd: 0,
        StateCd: 2,
        StateCdDesc: "Ready",
        ItemId: "SEMI001",
        ItemDesc: "Semielaborado 1",
        QtyReqd: 400,
        QtyProd: 0,
        Duracion: 45.193220338983,
        Personas: 1,
        posiblesVelocidades: [
          {
            personas: 1,
            velocidad: 66.66,
          },
          {
            personas: 2,
            velocidad: 33.33,
          },
          {
            personas: 3,
            velocidad: 22.22,
          },
          {
            personas: 4,
            velocidad: 11.1,
          },
        ],
        FactorOEE: 0.59,
        matriculasCargadas: false,
        SchedStartTimeLocal: "2022-03-19T14:22:43",
        SchedFinishTimeLocal: "2022-03-19T15:07:54",
        ActStartTimeLocal: "0001-01-01T00:00:00",
        ActStartTimeUTC: "0001-01-01T00:00:00",
        JobPos: null,
      },
      {
        WoId: "20220319142243",
        OperId: "NETEJA",
        SeqNo: 0,
        RowId: 100,
        SeqNoRelacionadoSpare3: 0,
        debugSpare3: null,
        JobDesc: null,
        init_EntId: 5,
        init_EntName: "AreaSemielaborado",
        target_EntId: 6,
        target_EntName: "L001",
        run_EntId: 0,
        run_EntName: null,
        WoStateCd: 0,
        StateCd: 2,
        StateCdDesc: "Ready",
        ItemId: "SEMI001",
        ItemDesc: "Semielaborado 1",
        QtyReqd: 1,
        QtyProd: 0,
        Duracion: 12,
        Personas: 1,
        posiblesVelocidades: [
          {
            personas: 1,
            velocidad: 0,
          },
        ],
        FactorOEE: 1,
        matriculasCargadas: false,
        SchedStartTimeLocal: "2022-03-19T15:07:54",
        SchedFinishTimeLocal: "2022-03-19T15:19:54",
        ActStartTimeLocal: "0001-01-01T00:00:00",
        ActStartTimeUTC: "0001-01-01T00:00:00",
        JobPos: null,
      },
      {
        WoId: "20220321120714",
        OperId: "AreaSemielaborado",
        SeqNo: 0,
        RowId: 103,
        SeqNoRelacionadoSpare3: 0,
        debugSpare3: null,
        JobDesc: null,
        init_EntId: 5,
        init_EntName: "AreaSemielaborado",
        target_EntId: 5,
        target_EntName: "AreaSemielaborado",
        run_EntId: 0,
        run_EntName: null,
        WoStateCd: 0,
        StateCd: 1,
        StateCdDesc: "New",
        ItemId: "SEMI001",
        ItemDesc: "Semielaborado 1",
        QtyReqd: 200,
        QtyProd: 0,
        Duracion: 22.5966101694915,
        Personas: 1,
        posiblesVelocidades: [
          {
            personas: 1,
            velocidad: 66.66,
          },
          {
            personas: 2,
            velocidad: 33.33,
          },
          {
            personas: 3,
            velocidad: 22.22,
          },
          {
            personas: 4,
            velocidad: 11.1,
          },
        ],
        FactorOEE: 0.59,
        matriculasCargadas: false,
        SchedStartTimeLocal: "2022-03-21T12:07:14",
        SchedFinishTimeLocal: "2022-03-21T12:29:49",
        ActStartTimeLocal: "0001-01-01T00:00:00",
        ActStartTimeUTC: "0001-01-01T00:00:00",
        JobPos: null,
      },
      {
        WoId: "20220321120714",
        OperId: "NETEJA",
        SeqNo: 0,
        RowId: 104,
        SeqNoRelacionadoSpare3: 0,
        debugSpare3: null,
        JobDesc: null,
        init_EntId: 5,
        init_EntName: "AreaSemielaborado",
        target_EntId: 5,
        target_EntName: "AreaSemielaborado",
        run_EntId: 0,
        run_EntName: null,
        WoStateCd: 0,
        StateCd: 1,
        StateCdDesc: "New",
        ItemId: "SEMI001",
        ItemDesc: "Semielaborado 1",
        QtyReqd: 1,
        QtyProd: 0,
        Duracion: 12,
        Personas: 1,
        posiblesVelocidades: [
          {
            personas: 1,
            velocidad: 0,
          },
        ],
        FactorOEE: 1,
        matriculasCargadas: false,
        SchedStartTimeLocal: "2022-03-21T12:29:49",
        SchedFinishTimeLocal: "2022-03-21T12:41:49",
        ActStartTimeLocal: "0001-01-01T00:00:00",
        ActStartTimeUTC: "0001-01-01T00:00:00",
        JobPos: null,
      },
      {
        WoId: "SANTI000000",
        OperId: "AreaSemielaborado",
        SeqNo: 0,
        RowId: 95,
        SeqNoRelacionadoSpare3: 0,
        debugSpare3: null,
        JobDesc: null,
        init_EntId: 5,
        init_EntName: "AreaSemielaborado",
        target_EntId: 7,
        target_EntName: "L002",
        run_EntId: 7,
        run_EntName: "L002",
        WoStateCd: 0,
        StateCd: 3,
        StateCdDesc: "Running",
        ItemId: "SEMI001",
        ItemDesc: "Semielaborado 1",
        QtyReqd: 1200,
        QtyProd: 0,
        Duracion: 5824.166912,
        Personas: 1,
        posiblesVelocidades: [
          {
            personas: 1,
            velocidad: 66.66,
          },
          {
            personas: 2,
            velocidad: 33.33,
          },
          {
            personas: 3,
            velocidad: 22.22,
          },
          {
            personas: 4,
            velocidad: 11.1,
          },
        ],
        FactorOEE: 0.59,
        matriculasCargadas: false,
        SchedStartTimeLocal: "2022-03-17T08:00:00",
        SchedFinishTimeLocal: "2022-03-21T12:50:11",
        ActStartTimeLocal: "0001-01-01T00:00:00",
        ActStartTimeUTC: "0001-01-01T00:00:00",
        JobPos: null,
      },
      {
        WoId: "SANTI000000",
        OperId: "NETEJA",
        SeqNo: 0,
        RowId: 96,
        SeqNoRelacionadoSpare3: 0,
        debugSpare3: null,
        JobDesc: null,
        init_EntId: 5,
        init_EntName: "AreaSemielaborado",
        target_EntId: 7,
        target_EntName: "L002",
        run_EntId: 0,
        run_EntName: null,
        WoStateCd: 0,
        StateCd: 2,
        StateCdDesc: "Ready",
        ItemId: "SEMI001",
        ItemDesc: "Semielaborado 1",
        QtyReqd: 1,
        QtyProd: 0,
        Duracion: 12,
        Personas: 1,
        posiblesVelocidades: [
          {
            personas: 1,
            velocidad: 0,
          },
        ],
        FactorOEE: 1,
        matriculasCargadas: false,
        SchedStartTimeLocal: "2022-03-21T12:50:11",
        SchedFinishTimeLocal: "2022-03-21T13:02:11",
        ActStartTimeLocal: "0001-01-01T00:00:00",
        ActStartTimeUTC: "0001-01-01T00:00:00",
        JobPos: null,
      },
      {
        WoId: "20220310S000",
        OperId: "NETEJA",
        SeqNo: 0,
        RowId: 30,
        SeqNoRelacionadoSpare3: 0,
        debugSpare3: null,
        JobDesc: null,
        init_EntId: 5,
        init_EntName: "AreaSemielaborado",
        target_EntId: 6,
        target_EntName: "L001",
        run_EntId: 0,
        run_EntName: null,
        WoStateCd: 0,
        StateCd: 2,
        StateCdDesc: "Ready",
        ItemId: "SEMI001",
        ItemDesc: "Semielaborado 1",
        QtyReqd: 1,
        QtyProd: 0,
        Duracion: 0,
        Personas: 1,
        posiblesVelocidades: [
          {
            personas: 1,
            velocidad: 0,
          },
        ],
        FactorOEE: 1,
        matriculasCargadas: false,
        SchedStartTimeLocal: "2022-03-19T13:43:01",
        SchedFinishTimeLocal: "2022-03-19T13:43:01",
        ActStartTimeLocal: "0001-01-01T00:00:00",
        ActStartTimeUTC: "0001-01-01T00:00:00",
        JobPos: null,
      },
      {
        WoId: "20220319142243",
        OperId: "AreaSemielaborado",
        SeqNo: 0,
        RowId: 99,
        SeqNoRelacionadoSpare3: 0,
        debugSpare3: null,
        JobDesc: null,
        init_EntId: 5,
        init_EntName: "AreaSemielaborado",
        target_EntId: 6,
        target_EntName: "L001",
        run_EntId: 0,
        run_EntName: null,
        WoStateCd: 0,
        StateCd: 2,
        StateCdDesc: "Ready",
        ItemId: "SEMI001",
        ItemDesc: "Semielaborado 1",
        QtyReqd: 400,
        QtyProd: 0,
        Duracion: 45.193220338983,
        Personas: 1,
        posiblesVelocidades: [
          {
            personas: 1,
            velocidad: 66.66,
          },
          {
            personas: 2,
            velocidad: 33.33,
          },
          {
            personas: 3,
            velocidad: 22.22,
          },
          {
            personas: 4,
            velocidad: 11.1,
          },
        ],
        FactorOEE: 0.59,
        matriculasCargadas: false,
        SchedStartTimeLocal: "2022-03-19T14:22:43",
        SchedFinishTimeLocal: "2022-03-19T15:07:54",
        ActStartTimeLocal: "0001-01-01T00:00:00",
        ActStartTimeUTC: "0001-01-01T00:00:00",
        JobPos: null,
      },
      {
        WoId: "20220319142243",
        OperId: "NETEJA",
        SeqNo: 0,
        RowId: 100,
        SeqNoRelacionadoSpare3: 0,
        debugSpare3: null,
        JobDesc: null,
        init_EntId: 5,
        init_EntName: "AreaSemielaborado",
        target_EntId: 6,
        target_EntName: "L001",
        run_EntId: 0,
        run_EntName: null,
        WoStateCd: 0,
        StateCd: 2,
        StateCdDesc: "Ready",
        ItemId: "SEMI001",
        ItemDesc: "Semielaborado 1",
        QtyReqd: 1,
        QtyProd: 0,
        Duracion: 12,
        Personas: 1,
        posiblesVelocidades: [
          {
            personas: 1,
            velocidad: 0,
          },
        ],
        FactorOEE: 1,
        matriculasCargadas: false,
        SchedStartTimeLocal: "2022-03-19T15:07:54",
        SchedFinishTimeLocal: "2022-03-19T15:19:54",
        ActStartTimeLocal: "0001-01-01T00:00:00",
        ActStartTimeUTC: "0001-01-01T00:00:00",
        JobPos: null,
      },
      {
        WoId: "20220321120714",
        OperId: "AreaSemielaborado",
        SeqNo: 0,
        RowId: 103,
        SeqNoRelacionadoSpare3: 0,
        debugSpare3: null,
        JobDesc: null,
        init_EntId: 5,
        init_EntName: "AreaSemielaborado",
        target_EntId: 5,
        target_EntName: "AreaSemielaborado",
        run_EntId: 0,
        run_EntName: null,
        WoStateCd: 0,
        StateCd: 1,
        StateCdDesc: "New",
        ItemId: "SEMI001",
        ItemDesc: "Semielaborado 1",
        QtyReqd: 200,
        QtyProd: 0,
        Duracion: 22.5966101694915,
        Personas: 1,
        posiblesVelocidades: [
          {
            personas: 1,
            velocidad: 66.66,
          },
          {
            personas: 2,
            velocidad: 33.33,
          },
          {
            personas: 3,
            velocidad: 22.22,
          },
          {
            personas: 4,
            velocidad: 11.1,
          },
        ],
        FactorOEE: 0.59,
        matriculasCargadas: false,
        SchedStartTimeLocal: "2022-03-21T12:07:14",
        SchedFinishTimeLocal: "2022-03-21T12:29:49",
        ActStartTimeLocal: "0001-01-01T00:00:00",
        ActStartTimeUTC: "0001-01-01T00:00:00",
        JobPos: null,
      },
      {
        WoId: "20220321120714",
        OperId: "NETEJA",
        SeqNo: 0,
        RowId: 104,
        SeqNoRelacionadoSpare3: 0,
        debugSpare3: null,
        JobDesc: null,
        init_EntId: 5,
        init_EntName: "AreaSemielaborado",
        target_EntId: 5,
        target_EntName: "AreaSemielaborado",
        run_EntId: 0,
        run_EntName: null,
        WoStateCd: 0,
        StateCd: 1,
        StateCdDesc: "New",
        ItemId: "SEMI001",
        ItemDesc: "Semielaborado 1",
        QtyReqd: 1,
        QtyProd: 0,
        Duracion: 12,
        Personas: 1,
        posiblesVelocidades: [
          {
            personas: 1,
            velocidad: 0,
          },
        ],
        FactorOEE: 1,
        matriculasCargadas: false,
        SchedStartTimeLocal: "2022-03-21T12:29:49",
        SchedFinishTimeLocal: "2022-03-21T12:41:49",
        ActStartTimeLocal: "0001-01-01T00:00:00",
        ActStartTimeUTC: "0001-01-01T00:00:00",
        JobPos: null,
      },
      {
        WoId: "SANTI000000",
        OperId: "AreaSemielaborado",
        SeqNo: 0,
        RowId: 95,
        SeqNoRelacionadoSpare3: 0,
        debugSpare3: null,
        JobDesc: null,
        init_EntId: 5,
        init_EntName: "AreaSemielaborado",
        target_EntId: 7,
        target_EntName: "L002",
        run_EntId: 7,
        run_EntName: "L002",
        WoStateCd: 0,
        StateCd: 3,
        StateCdDesc: "Running",
        ItemId: "SEMI001",
        ItemDesc: "Semielaborado 1",
        QtyReqd: 1200,
        QtyProd: 0,
        Duracion: 5824.166912,
        Personas: 1,
        posiblesVelocidades: [
          {
            personas: 1,
            velocidad: 66.66,
          },
          {
            personas: 2,
            velocidad: 33.33,
          },
          {
            personas: 3,
            velocidad: 22.22,
          },
          {
            personas: 4,
            velocidad: 11.1,
          },
        ],
        FactorOEE: 0.59,
        matriculasCargadas: false,
        SchedStartTimeLocal: "2022-03-17T08:00:00",
        SchedFinishTimeLocal: "2022-03-21T12:50:11",
        ActStartTimeLocal: "0001-01-01T00:00:00",
        ActStartTimeUTC: "0001-01-01T00:00:00",
        JobPos: null,
      },
      {
        WoId: "SANTI000000",
        OperId: "NETEJA",
        SeqNo: 0,
        RowId: 96,
        SeqNoRelacionadoSpare3: 0,
        debugSpare3: null,
        JobDesc: null,
        init_EntId: 5,
        init_EntName: "AreaSemielaborado",
        target_EntId: 7,
        target_EntName: "L002",
        run_EntId: 0,
        run_EntName: null,
        WoStateCd: 0,
        StateCd: 2,
        StateCdDesc: "Ready",
        ItemId: "SEMI001",
        ItemDesc: "Semielaborado 1",
        QtyReqd: 1,
        QtyProd: 0,
        Duracion: 12,
        Personas: 1,
        posiblesVelocidades: [
          {
            personas: 1,
            velocidad: 0,
          },
        ],
        FactorOEE: 1,
        matriculasCargadas: false,
        SchedStartTimeLocal: "2022-03-21T12:50:11",
        SchedFinishTimeLocal: "2022-03-21T13:02:11",
        ActStartTimeLocal: "0001-01-01T00:00:00",
        ActStartTimeUTC: "0001-01-01T00:00:00",
        JobPos: null,
      },
      {
        WoId: "20220310S000",
        OperId: "NETEJA",
        SeqNo: 0,
        RowId: 30,
        SeqNoRelacionadoSpare3: 0,
        debugSpare3: null,
        JobDesc: null,
        init_EntId: 5,
        init_EntName: "AreaSemielaborado",
        target_EntId: 6,
        target_EntName: "L001",
        run_EntId: 0,
        run_EntName: null,
        WoStateCd: 0,
        StateCd: 2,
        StateCdDesc: "Ready",
        ItemId: "SEMI001",
        ItemDesc: "Semielaborado 1",
        QtyReqd: 1,
        QtyProd: 0,
        Duracion: 0,
        Personas: 1,
        posiblesVelocidades: [
          {
            personas: 1,
            velocidad: 0,
          },
        ],
        FactorOEE: 1,
        matriculasCargadas: false,
        SchedStartTimeLocal: "2022-03-19T13:43:01",
        SchedFinishTimeLocal: "2022-03-19T13:43:01",
        ActStartTimeLocal: "0001-01-01T00:00:00",
        ActStartTimeUTC: "0001-01-01T00:00:00",
        JobPos: null,
      },
      {
        WoId: "20220319142243",
        OperId: "AreaSemielaborado",
        SeqNo: 0,
        RowId: 99,
        SeqNoRelacionadoSpare3: 0,
        debugSpare3: null,
        JobDesc: null,
        init_EntId: 5,
        init_EntName: "AreaSemielaborado",
        target_EntId: 6,
        target_EntName: "L001",
        run_EntId: 0,
        run_EntName: null,
        WoStateCd: 0,
        StateCd: 2,
        StateCdDesc: "Ready",
        ItemId: "SEMI001",
        ItemDesc: "Semielaborado 1",
        QtyReqd: 400,
        QtyProd: 0,
        Duracion: 45.193220338983,
        Personas: 1,
        posiblesVelocidades: [
          {
            personas: 1,
            velocidad: 66.66,
          },
          {
            personas: 2,
            velocidad: 33.33,
          },
          {
            personas: 3,
            velocidad: 22.22,
          },
          {
            personas: 4,
            velocidad: 11.1,
          },
        ],
        FactorOEE: 0.59,
        matriculasCargadas: false,
        SchedStartTimeLocal: "2022-03-19T14:22:43",
        SchedFinishTimeLocal: "2022-03-19T15:07:54",
        ActStartTimeLocal: "0001-01-01T00:00:00",
        ActStartTimeUTC: "0001-01-01T00:00:00",
        JobPos: null,
      },
      {
        WoId: "20220319142243",
        OperId: "NETEJA",
        SeqNo: 0,
        RowId: 100,
        SeqNoRelacionadoSpare3: 0,
        debugSpare3: null,
        JobDesc: null,
        init_EntId: 5,
        init_EntName: "AreaSemielaborado",
        target_EntId: 6,
        target_EntName: "L001",
        run_EntId: 0,
        run_EntName: null,
        WoStateCd: 0,
        StateCd: 2,
        StateCdDesc: "Ready",
        ItemId: "SEMI001",
        ItemDesc: "Semielaborado 1",
        QtyReqd: 1,
        QtyProd: 0,
        Duracion: 12,
        Personas: 1,
        posiblesVelocidades: [
          {
            personas: 1,
            velocidad: 0,
          },
        ],
        FactorOEE: 1,
        matriculasCargadas: false,
        SchedStartTimeLocal: "2022-03-19T15:07:54",
        SchedFinishTimeLocal: "2022-03-19T15:19:54",
        ActStartTimeLocal: "0001-01-01T00:00:00",
        ActStartTimeUTC: "0001-01-01T00:00:00",
        JobPos: null,
      },
      {
        WoId: "20220321120714",
        OperId: "AreaSemielaborado",
        SeqNo: 0,
        RowId: 103,
        SeqNoRelacionadoSpare3: 0,
        debugSpare3: null,
        JobDesc: null,
        init_EntId: 5,
        init_EntName: "AreaSemielaborado",
        target_EntId: 5,
        target_EntName: "AreaSemielaborado",
        run_EntId: 0,
        run_EntName: null,
        WoStateCd: 0,
        StateCd: 1,
        StateCdDesc: "New",
        ItemId: "SEMI001",
        ItemDesc: "Semielaborado 1",
        QtyReqd: 200,
        QtyProd: 0,
        Duracion: 22.5966101694915,
        Personas: 1,
        posiblesVelocidades: [
          {
            personas: 1,
            velocidad: 66.66,
          },
          {
            personas: 2,
            velocidad: 33.33,
          },
          {
            personas: 3,
            velocidad: 22.22,
          },
          {
            personas: 4,
            velocidad: 11.1,
          },
        ],
        FactorOEE: 0.59,
        matriculasCargadas: false,
        SchedStartTimeLocal: "2022-03-21T12:07:14",
        SchedFinishTimeLocal: "2022-03-21T12:29:49",
        ActStartTimeLocal: "0001-01-01T00:00:00",
        ActStartTimeUTC: "0001-01-01T00:00:00",
        JobPos: null,
      },
      {
        WoId: "20220321120714",
        OperId: "NETEJA",
        SeqNo: 0,
        RowId: 104,
        SeqNoRelacionadoSpare3: 0,
        debugSpare3: null,
        JobDesc: null,
        init_EntId: 5,
        init_EntName: "AreaSemielaborado",
        target_EntId: 5,
        target_EntName: "AreaSemielaborado",
        run_EntId: 0,
        run_EntName: null,
        WoStateCd: 0,
        StateCd: 1,
        StateCdDesc: "New",
        ItemId: "SEMI001",
        ItemDesc: "Semielaborado 1",
        QtyReqd: 1,
        QtyProd: 0,
        Duracion: 12,
        Personas: 1,
        posiblesVelocidades: [
          {
            personas: 1,
            velocidad: 0,
          },
        ],
        FactorOEE: 1,
        matriculasCargadas: false,
        SchedStartTimeLocal: "2022-03-21T12:29:49",
        SchedFinishTimeLocal: "2022-03-21T12:41:49",
        ActStartTimeLocal: "0001-01-01T00:00:00",
        ActStartTimeUTC: "0001-01-01T00:00:00",
        JobPos: null,
      },
      {
        WoId: "SANTI000000",
        OperId: "AreaSemielaborado",
        SeqNo: 0,
        RowId: 95,
        SeqNoRelacionadoSpare3: 0,
        debugSpare3: null,
        JobDesc: null,
        init_EntId: 5,
        init_EntName: "AreaSemielaborado",
        target_EntId: 7,
        target_EntName: "L002",
        run_EntId: 7,
        run_EntName: "L002",
        WoStateCd: 0,
        StateCd: 3,
        StateCdDesc: "Running",
        ItemId: "SEMI001",
        ItemDesc: "Semielaborado 1",
        QtyReqd: 1200,
        QtyProd: 0,
        Duracion: 5824.166912,
        Personas: 1,
        posiblesVelocidades: [
          {
            personas: 1,
            velocidad: 66.66,
          },
          {
            personas: 2,
            velocidad: 33.33,
          },
          {
            personas: 3,
            velocidad: 22.22,
          },
          {
            personas: 4,
            velocidad: 11.1,
          },
        ],
        FactorOEE: 0.59,
        matriculasCargadas: false,
        SchedStartTimeLocal: "2022-03-17T08:00:00",
        SchedFinishTimeLocal: "2022-03-21T12:50:11",
        ActStartTimeLocal: "0001-01-01T00:00:00",
        ActStartTimeUTC: "0001-01-01T00:00:00",
        JobPos: null,
      },
      {
        WoId: "SANTI000000",
        OperId: "NETEJA",
        SeqNo: 0,
        RowId: 96,
        SeqNoRelacionadoSpare3: 0,
        debugSpare3: null,
        JobDesc: null,
        init_EntId: 5,
        init_EntName: "AreaSemielaborado",
        target_EntId: 7,
        target_EntName: "L002",
        run_EntId: 0,
        run_EntName: null,
        WoStateCd: 0,
        StateCd: 2,
        StateCdDesc: "Ready",
        ItemId: "SEMI001",
        ItemDesc: "Semielaborado 1",
        QtyReqd: 1,
        QtyProd: 0,
        Duracion: 12,
        Personas: 1,
        posiblesVelocidades: [
          {
            personas: 1,
            velocidad: 0,
          },
        ],
        FactorOEE: 1,
        matriculasCargadas: false,
        SchedStartTimeLocal: "2022-03-21T12:50:11",
        SchedFinishTimeLocal: "2022-03-21T13:02:11",
        ActStartTimeLocal: "0001-01-01T00:00:00",
        ActStartTimeUTC: "0001-01-01T00:00:00",
        JobPos: null,
      },
    ],
    lineas: [
      {
        entId: 6,
        entName: "L001",
        description: "Semielaborado 1",
        operacion: false,
        ordenes: [],
      },
      {
        entId: 7,
        entName: "L002",
        description: "Semielaborado 2",
        operacion: false,
        ordenes: [],
      },
    ],
  },
];
